### ISSUE TITLE
Controller needs permission to list (and probably get/watch) ServiceAccounts and RoleBindings

### ISSUE THREAD

**Issue by kalantar** [llm-d/llm-d-model-service#111]
**Describe the bug**
controller log has error messages that it can't list serviceaccounts or rolebindings

**Additional context**
This is the prod image

Problem is generated `ClusterRole` `model-service-manager-role` (a) does not give the controller these permissions and (b) misspells serviceaccounts and rolebindings (trailing s is missing).

Code update should be made here: https://github.com/neuralmagic/llm-d-model-service/blob/dev/internal/controller/modelservice_controller.go#L139-L140

In the meantime, we can use this `ClusterRole` definition:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelservice-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - get
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - patch
  - update
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferencemodel
  - inferencepool
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm-d.ai
  resources:
  - modelservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm-d.ai
  resources:
  - modelservices/finalizers
  verbs:
  - update
- apiGroups:
  - llm-d.ai
  resources:
  - modelservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - get
  - watch
  - create
  - delete
  - update
  - patch
```
