### ISSUE TITLE
Allow templating of port numbers

### ISSUE THREAD

**Issue by kalantar** [llm-d/llm-d-model-service#122]
**Is your feature request related to a problem? Please describe.**
Configuring baseconfig to be consistent is hard. For example, the proxy on the decode pod has:
```
              args:
                - "--port=8000"
                - "--vllm-port=8200"
                - "--connector=nixl"
              ports:
                - containerPort: 8000
                  protocol: TCP
```
The `vllm` container on the decode pod must listen on port 8200:
```
              args:
                - "--port"
                - "8200"
```
On the other hand, the vllm container on the prefilll pod should listen on port 8000:
```
              args:
                - "--port"
                - "8000"
```
since there is no proxy.

The `8000` in both pods corresponds to the `targetPortNumber` in the `InferencePool`.

**Describe the solution approach you'd like**
Introduce ports in the `routing` section of the msvc. Allow template variables to reference these.
For example, a full list might be:
```
routing:
  ports:
  - name: model-svc
    value: 8000
  - name: intermediary
    value: 8200
```
which can then be referred to, for example, as: `{{ .GetPort "model-svc" }}` where `.GetPort` is a method we implement. Not sure if the sprig framework already provides a suitable method.
