### ISSUE TITLE
Implement complete behaviors for HF URI

### ISSUE THREAD

**Issue by sriumcp** [llm-d/llm-d-model-service#171]
**Is your feature request related to a problem? Please describe.**
Currently, the `hf://...` uri behavior is not implemented.

**Describe the solution approach you'd like**
Consider the following sub-fields in an MSVC

```yaml
 modelArtifacts:
    uri: hf://facebook/opt-125m
    authSecretName: mytokens
    size: 5Gi
containers:
    - name: vllm
      args:
      - "{{ .HFModelName }}"
      mountModelVolume: true
```

The pod-spec generated out of msvc should look like this.

```yaml
containers:
    - name: vllm
      args:
      - "{{ .HFModelName }}"
      - "--hf_token"
      - "$HF_TOKEN"
      - "--download-dir" 
      - /models # this must always be the download-dir arg for hf:// URIs.
      env:
      - name: HF_TOKEN
         valueFrom:
           secretKeyRef:
             name: "{{ .ModelArtifacts.AuthSecretName }}"
             key: HF_TOKEN      
      volumeMounts:
      - mountPath: /models # this must always be the model-storage mountPath for hf:// URIs.
        name: model-storage
    volumes:
    - name: model-storage
      emptyDir:
        sizeLimit: "{{ .ModelArtifacts.Size }}"
```

***

Note that the msvc resource specs (of which the above is a snippet) get mergo merged as usual into the baseconfig specs.

***

**Behind the scenes:**

The `.mountModelVolume: true` should induce the following behavior for the msvc generated deployment specs (this is even before the baseconfig merges).

1. Token and download dir args are created (and appended to whatever is already supplied in the original msvc spec)
2. The HF_TOKEN env variable gets created and name-merged into whatever envs are supplied already. Note that the template context has to be extended to include the entire `ModelArtifacts` struct as part of it, so that one can write "{{ .ModelArtifacts.AuthSecretName }}".
4. The container volume mount gets created.
5. The pod-spec volume gets created. Note that the template context has to be extended to include the entire `ModelArtifacts` struct as part of it, so that one can write "{{ .ModelArtifacts.Size }}".
