### ISSUE TITLE
Confirm complete behaviors for PVC URI

### ISSUE THREAD

**Issue by jgchn** [llm-d/llm-d-model-service#174]
**Is your feature request related to a problem? Please describe.**
Currently, the `pvc://...` uri behavior is not fully implemented.

**Describe the solution approach you'd like**
Consider the following sub-fields in an MSVC

```yaml
 modelArtifacts:
    uri: pvc://pvc-name/path/to/model
containers:
    - name: vllm
      args:
      # {{ .CompleteModelPath }} = /cache + /path/to/model
      - "{{ .CompleteModelPath }}"
      mountModelVolume: true
```

The pod-spec generated out of msvc should look like this.

```yaml
containers:
    - name: vllm
      args:
      # See example [here](https://docs.vllm.ai/en/v0.6.5/serving/distributed_serving.html#details-for-distributed-inference-and-serving) on argument when loading model from a local path
      - "{{ .CompleteModelPath }}" 
      volumeMounts:
      - mountPath: /cache # this is always be the model-storage mountPath for pvc:// URIs.
        name: model-storage
    volumes:
    - name: model-storage
       persistentVolumeClaims:
         claimName: pvc-name
```

***

Note that the msvc resource specs (of which the above is a snippet) get mergo merged as usual into the baseconfig specs.

***

**Behind the scenes:**

The `.mountModelVolume: true` should induce the following behavior for the msvc generated deployment specs (this is even before the baseconfig merges).

1. Volumes with the correct PVC and claimName is created 
2. volumeMountPath is added to the container where `.mountModelVolume: true`
