### ISSUE TITLE
MS enforces field `readinessProbe.grpc.service` and `livenessProbe.grpc.service` for epp deployment

### ISSUE THREAD

**Issue by Gregory-Pereira** [llm-d/llm-d-model-service#53]
In the MS base config we controll aspects of the `epp` deployment. However, the `name` of the `eppService` is determined by the controller after submitting a `modelservice` CR, because the controller uses the modelservice object to choose the service name: https://github.com/neuralmagic/llm-d-model-service/blob/dev/internal/controller/child_resources.go#L640. This will produce something model-dependent for the service name, in my case: 
```bash
 oc get services
NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
llama-32-3b-instruct-epp-service       NodePort    172.30.116.39    <none>        9002:31954/TCP       7m34
...
```

The deployment of the EPP object is defined in the baseconfig however, and so it won't be able to know what the service name will be. Here is the relevant excerpt from the baseconfig under `eppDeployment` :

```yaml
    apiVersion: apps/v1
    kind: Deployment
    spec:
      template:
        spec:
          serviceAccountName: endpoint-picker-sa # temporary workaround (see #52 )
          containers:
           - name: epp
              ...
              livenessProbe:
                failureThreshold: 3
                grpc:
                  port: 9003
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                grpc:
                  port: 9003
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
```
As you can see I have removed the `.spec.template.spec.containers.0.livenessProbe.grpc.service` and `.spec.template.spec.containers.0.readinessProbe.grpc.service` values which were previously there, specifically because this is not something we could specify in the base config. However, the controller automatically adds this back as part of the merge, producing the following in my deployment:

```yaml
      containers:
        - name: epp
           readinessProbe:
             grpc:
               port: 9003
               service: ''
           ...

           livenessProbe:
             grpc:
               port: 9003
               service: ''
```

Since it enforces the service name, and not just the port, this causes errors in the pod logs:

```log
{"level":"Level(-2)","ts":"2025-05-03T17:10:08Z","logger":"health","caller":"epp/health.go:37","msg":"gRPC health check not serving","service":""}
```

This causes shutdown and crashloop
