### ISSUE TITLE
CRITICAL: Modelservice CR + Base config container argument merge order for vllm container args

### ISSUE THREAD

**Issue by Gregory-Pereira** [llm-d/llm-d-model-service#57]
When running the vllm container, the model name to use or the model path is **a positional argument**. There are also no alternatives for serving a local model except the `--config` file merged in upstream vllm in 0.8.4, the `--model` flag only works with remote HF repo. When the modelservice controller merges the modelservice CR into the baseconfig it produces the following
```
      args:
        - '--port'
        - '8200'
        - '--kv-transfer-config'
        - '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_consumer","kv_connector_extra_config": {"discard_partial_chunks": false, "lmcache_rpc_port": "consumer1"}}'
        - /cache/models/meta-llama/Llama-32-3B-Instruct
        - '--served-model-name'
        - Llama-32-3B-Instruct
```
It always happens in this order (with the bottom 3 values coming from the modelservice CR itself) making me think that it is merging the `modelservice` CR **into** the base config to create the deployment. Because the HF model name or model Path is a positional argument, this will always crash. It will recognize `--port` and think its an HF repo, try to download the model and fail.

In our previous charts these args looked [this](https://github.com/neuralmagic/vllm-d-deployer/blob/9ed7cae27f37790e3f8fbc774fd9ca2f6c4c58b5/charts/llm-d/templates/modelservice/modelservice_cr.yaml#L34-L41) (and yes I confirmed the images were the same so it doesn’t pass values to vllm in a different way):

```
      args:
      - "{{ .Values.modelservice.sampleAppDeploy.modelPath }}"
      - "--served-model-name"
      - "{{ .Values.modelservice.sampleAppDeploy.modelName }}"
      -  "--port"
      -  "{{ .Values.modelservice.sampleAppDeploy.vllmProxyPort }}"
      - "--kv-transfer-config"
      - '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_producer", "kv_connector_extra_config": {"discard_partial_chunks": false, "lmcache_rpc_port": "producer1"}}'
```

Alternatively I tried to pass the model name in `command` so that the args would apply afterward, making it a valid positional argument, but the `modelservice` controller did not accept specifying those to the `prefill` and `decode` sections respectively:
```
W0503 14:42:17.325629   96997 warnings.go:70] unknown field "spec.decode.containers[0].command"
W0503 14:42:17.325706   96997 warnings.go:70] unknown field "spec.prefill.containers[0].command"
```

I did find it odd that modelservice did not accept `command` for the container, as its part of the valid podspec. This is how I was trying to pass it as command in the `modelservice` CR:

```yaml
{{- if .Values.sampleApplication.enabled -}}
apiVersion: llm-d.ai/v1alpha1
kind: ModelService
metadata:
  name: {{ include "sampleApplication.sanitizedModelName" . }}
spec:
  decoupleScaling: false
  baseConfigMapRef:
    name: {{ include "modelservice.fullname" . }}-basic-gpu-with-nixl-preset
  routing:
    modelName: {{ .Values.sampleApplication.modelName }}
  modelArtifacts:
    uri: {{ .Values.sampleApplication.modelArtifactUri }}
  decode:
    replicas: 1
    containers:
    - name: "vllm"
      command:
      - "vllm"
      - "serve"
      - {{ .Values.sampleApplication.modelPath | quote }}
      args:
      - "--served-model-name"
      - {{ .Values.sampleApplication.modelName }}
      resources: {{ .Values.sampleApplication.resources | toYaml | nindent 8 }}
  prefill:
    replicas: 1
    containers:
    - name: "vllm"
      command:
      - "vllm"
      - "serve"
      - {{ .Values.sampleApplication.modelPath | quote }}
      args:
      - "--served-model-name"
      - {{ .Values.sampleApplication.modelName }}
      resources: {{ .Values.sampleApplication.resources | toYaml | nindent 8 }}
```

I am not 100% certain using the command option would work, using model name as 1st positional argument is wonky but more robust.
